-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 20:54:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema users-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema users-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `users-db` DEFAULT CHARACTER SET utf8 ;
USE `users-db` ;

-- -----------------------------------------------------
-- Table `users-db`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users-db`.`Role` (
  `roleId` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users-db`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users-db`.`Department` (
  `departmentId` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`departmentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users-db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users-db`.`User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `roleId` INT NOT NULL,
  `departmentId` INT NOT NULL,
  `firstName` VARCHAR(80) NOT NULL,
  `lastName` VARCHAR(80) NOT NULL,
  `emailUser` VARCHAR(80) NOT NULL,
  `salary` DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `emailUser_UNIQUE` (`emailUser` ASC) VISIBLE,
  INDEX `fk_user_roles_idx` (`roleId` ASC) VISIBLE,
  INDEX `fk_User_Department1_idx` (`departmentId` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles`
    FOREIGN KEY (`roleId`)
    REFERENCES `users-db`.`Role` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Department1`
    FOREIGN KEY (`departmentId`)
    REFERENCES `users-db`.`Department` (`departmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
